name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Change if you use a different version

      - name: Build Go backend
        run: go build -v ./...

      - name: Trigger Render Deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1fam92li9vc739qu000?key=Wu065_lX3vQ
