name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build the app
      run: go build -v .

    - name: Run Tests
      run: go test ./...

    - name: Deploy to Render using deploy hook
      run: |
        curl -X POST "https://api.render.com/deploy/srv-d1fam92li9vc739qu000?key=Wu065_lX3vQ"
